specVersion: 1.0.0
name: acala-evm-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: Subquery Server for Pike Protocol
repository: https://github.com/nutsfinance/pike-subql
schema:
  file: ./schema.graphql
network:
  chainId: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: wss://acala-polkadot.api.onfinality.io/public-ws
  # Dictionary not currently supported
  # dictionary: https://api.subquery.network/sq/subquery/moonriver-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/AcalaEvm
    startBlock: 1571687
    processor:
      file: ./node_modules/@subql/acala-evm-processor/dist/bundle.js
      options:
        abi: comptroller
        address: '0x1aA5d813bA2BC2678b41Bd6AC8798909304a181f' # Comptroller
    assets:
      comptroller:
        file: ./src/abis/Comptroller.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleMarketListed
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - MarketListed(address)
        - handler: handleMarketEntered
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - MarketEntered(address,address)
        - handler: handleMarketExited
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - MarketExited(address,address)
        - handler: handleNewCloseFactor
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewCloseFactor(uint256,uint256)
        - handler: handleNewCollateralFactor
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewCollateralFactor(address,uint256,uint256)
        - handler: handleNewLiquidationIncentive
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewLiquidationIncentiveEventArgs(uint256,uint256)
        - handler: handleNewPriceOracle
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewPriceOracle(address,address)
  - kind: substrate/AcalaEvm
    startBlock: 1571687
    processor:
      file: ./node_modules/@subql/acala-evm-processor/dist/bundle.js
      options:
        abi: ctoken
        address: '0xde964267C24a408725A61AC2B3Fd4E95243Bf197' # pDOT
    assets:
      ctoken:
        file: ./src/abis/CToken.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Borrow(address,uint256,uint256,uint256)
        - handler: handleRepayBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - RepayBorrow(address,address,uint256,uint256,uint256)
        - handler: handleLiquidateBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - LiquidateBorrow(address,address,uint256,address,uint256)
        - handler: handleTransfer
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Transfer(address,address,uint256)
        - handler: handleAccrueInterest
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - AccrueInterest(uint256,uint256,uint256,uint256)
        - handler: handleNewReserveFactor
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewReserveFactor(address,address)
        - handler: handleNewInterestRateModel
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewInterestRateModel(address,address)
  - kind: substrate/AcalaEvm
    startBlock: 1571687
    processor:
      file: ./node_modules/@subql/acala-evm-processor/dist/bundle.js
      options:
        abi: ctoken
        address: '0x6f58EDA1638eDe4dB99ea698eF6be851eDd192B3' # pLDOT
    assets:
      ctoken:
        file: ./src/abis/CToken.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Borrow(address,uint256,uint256,uint256)
        - handler: handleRepayBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - RepayBorrow(address,address,uint256,uint256,uint256)
        - handler: handleLiquidateBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - LiquidateBorrow(address,address,uint256,address,uint256)
        - handler: handleTransfer
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Transfer(address,address,uint256)
        - handler: handleAccrueInterest
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - AccrueInterest(uint256,uint256,uint256,uint256)
        - handler: handleNewReserveFactor
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewReserveFactor(address,address)
        - handler: handleNewInterestRateModel
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewInterestRateModel(address,address)
  - kind: substrate/AcalaEvm
    startBlock: 1571687
    processor:
      file: ./node_modules/@subql/acala-evm-processor/dist/bundle.js
      options:
        abi: ctoken
        address: '0x3B8184054b67f95069aD54D66F53C13eE7B267C3' # pTDOT
    assets:
      ctoken:
        file: ./src/abis/CToken.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Borrow(address,uint256,uint256,uint256)
        - handler: handleRepayBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - RepayBorrow(address,address,uint256,uint256,uint256)
        - handler: handleLiquidateBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - LiquidateBorrow(address,address,uint256,address,uint256)
        - handler: handleTransfer
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Transfer(address,address,uint256)
        - handler: handleAccrueInterest
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - AccrueInterest(uint256,uint256,uint256,uint256)
        - handler: handleNewReserveFactor
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewReserveFactor(address,address)
        - handler: handleNewInterestRateModel
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewInterestRateModel(address,address)
  - kind: substrate/AcalaEvm
    startBlock: 1571687
    processor:
      file: ./node_modules/@subql/acala-evm-processor/dist/bundle.js
      options:
        abi: ctoken
        address: '0x53CFdfD2C7387EB9409B8Fe63Eb99D2081718a12' # pAUSD
    assets:
      ctoken:
        file: ./src/abis/CToken.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Borrow(address,uint256,uint256,uint256)
        - handler: handleRepayBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - RepayBorrow(address,address,uint256,uint256,uint256)
        - handler: handleLiquidateBorrow
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - LiquidateBorrow(address,address,uint256,address,uint256)
        - handler: handleTransfer
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Transfer(address,address,uint256)
        - handler: handleAccrueInterest
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - AccrueInterest(uint256,uint256,uint256,uint256)
        - handler: handleNewReserveFactor
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewReserveFactor(address,address)
        - handler: handleNewInterestRateModel
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - NewInterestRateModel(address,address)